# Generated by Django 4.0 on 2022-03-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_alter_notes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
